### ISSUE TITLE
 write_to_testcase() Error

### ISSUE THREAD

**Issue by JsHuang** [linhlhq/TinyAFL#7]
Using TinyAFL ofen encountered ` write_to_testcase()` permision error and fuzzing finished quickly
```
[-]  SYSTEM ERROR : Unable to create 'R:\out\.cur_input'
    Stop location : write_to_testcase(), E:\01-FuzzTools\TinyAFL-master\afl-fuzz.cpp:2270
       OS message : Permission denied
```
I'm sure the current user has permison in the dest folder， and this is not happend in the starting phase of fuzzing.

**Comment by wangkai0351** [comment]
Yes, I also encountered this problem when using tinyafl on the Windows platform, and I am actively debugging to solve this problem

**Comment by linhlhq** [comment]
Hi,

I have updated to version 1.2. Now TinyAFL supports shared memory.
